data_dict = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Algeria": "Algiers",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Antigua and Barbuda": "Saint Johns",
    "Argentina": "Buenos Aires",
    "Armenia": "Yerevan",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Azerbaijan": "Baku",
    "Bahamas": "Nassau",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Barbados": "Bridgetown",
    "Belarus": "Minsk",
    "Belgium": "Brussels",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bhutan": "Thimphu",
    "Bolivia": "La Paz",
    "Bosnia and Herzegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Brazil": "Brasilia",
    "Brunei": "Bandar Seri Begawan",
    "Bulgaria": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Bujumbura",
    "Cabo Verde": "Praia",
    "Cambodia": "Phnom Penh",
    "Cameroon": "Yaounde",
    "Canada": "Ottawa",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Chile": "Santiago",
    "China": "Beijing",
    "Colombia": "Bogota",
    "Comoros": "Moroni",
    "Costa Rica": "San Jose",
    "Cote d'Ivoire": "Yamoussoukro",
    "Croatia": "Zagreb",
    "Cuba": "Havana",
    "Cyprus": "Nicosia",
    "Czech Republic": "Prague",
    "Democratic Republic of the Congo": "Kinshasa",
    "Denmark": "Copenhagen",
    "Djibouti": "Djibouti (city)",
    "Dominica": "Roseau",
    "Dominican Republic": "Santo Domingo",
    "Ecuador": "Quito",
    "Egypt": "Cairo",
    "El Salvador": "San Salvador",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Estonia": "Tallinn",
    "Ethiopia": "Addis Ababa",
    "Fiji": "Suva",
    "Finland": "Helsinki",
    "France": "Paris",
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Georgia": "Tbilisi",
    "Germany": "Berlin",
    "Ghana": "Accra",
    "Greece": "Athens",
    "Grenada": "Saint Georges",
    "Guatemala": "Guatemala City",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Hungary": "Budapest",
    "Iceland": "Reykjavik",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Israel": "Jerusalem",
    "Italy": "Rome",
    "Jamaica": "Kingston",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kenya": "Nairobi",
    "Kiribati": "South Tarawa",
    "Kosovo": "Pristina",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Latvia": "Riga",
    "Lebanon": "Beirut",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg",
    "Macedonia": "Skopje",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaysia": "Kuala Lumpur",
    "Maldives": "Male",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshall Islands": "Majuro",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Mexico": "Mexico City",
    "Micronesia": "Palikir",
    "Moldova": "Chisinau",
    "Monaco": "Monaco",
    "Mongolia": "Ulaanbaatar",
    "Montenegro": "Podgorica",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Myanmar (Burma)": "Naypyidaw",
    "Namibia": "Windhoek",
    "Nauru": "Yaren District",
    "Nepal": "Kathmandu",
    "Netherlands": "Amsterdam",
    "New Zealand": "Wellington",
    "Nicaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "North Korea": "Pyongyang",
    "Norway": "Oslo",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Palau": "Ngerulmud",
    "Palestine": "Jerusalem / Ramallah",
    "Panama": "Panama City",
    "Papua New Guinea": "Port Moresby",
    "Paraguay": "Asuncion",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Qatar": "Doha",
    "Republic of the Congo": "Brazzaville",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "Rwanda": "Kigali",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Vincent and the Grenadines": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome",
    "Saudi Arabia": "Riyadh",
    "Senegal": "Dakar",
    "Serbia": "Belgrade",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapore": "Singapore",
    "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana",
    "Solomon Islands": "Honiara",
    "Somalia": "Mogadishu",
    "South Africa": "Pretoria",
    "South Korea": "Seoul",
    "South Sudan": "Juba",
    "Spain": "Madrid",
    "Sri Lanka": "Sri Jayawardenepura Kotte",
    "Sudan": "Khartoum",
    "Suriname": "Paramaribo",
    "Swaziland": "Mbabane",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Syria": "Damascus",
    "Taiwan": "Taipei",
    "Tajikistan": "Dushanbe",
    "Tanzania": "Dodoma",
    "Thailand": "Bangkok",
    "Timor-Leste": "Dili",
    "Togo": "Lome",
    "Tonga": "Nukuʻalofa",
    "Trinidad and Tobago": "Port of Spain",
    "Tunisia": "Tunis",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "Tuvalu": "Funafuti",
    "Uganda": "Kampala",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States of America": "Washington, D.C.",
    "Uruguay": "Montevideo",
    "Uzbekistan": "Tashkent",
    "Vanuatu": "Port Vila",
    "Vatican City (Holy See)": "Vatican City",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoi",
    "Yemen": "Sanaa",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare"
}


# this may come in handy later
# def make_tup_list():
#     tup_list = []
#     for key, val in data_dict.items():
#         tup_list.append((key, val))
#     print(tup_list)

list_of_tups = [('Japan', 'Tokyo'), ('Eritrea', 'Asmara'), ('Myanmar (Burma)', 'Naypyidaw'), ('Bahamas', 'Nassau'), ('Guinea', 'Conakry'), ('Kyrgyzstan', 'Bishkek'), ('Kazakhstan', 'Astana'), ('Bolivia', 'La Paz'), ('Ethiopia', 'Addis Ababa'), ('Tajikistan', 'Dushanbe'), ('Dominica', 'Roseau'), ('Equatorial Guinea', 'Malabo'), ('Nauru', 'Yaren District'), ('China', 'Beijing'), ('Malawi', 'Lilongwe'), ('Zambia', 'Lusaka'), ('France', 'Paris'), ('Zimbabwe', 'Harare'), ('New Zealand', 'Wellington'), ('Suriname', 'Paramaribo'), ('Madagascar', 'Antananarivo'), ('Norway', 'Oslo'), ('Palau', 'Ngerulmud'), ('Israel', 'Jerusalem'), ('Brazil', 'Brasilia'), ('Rwanda', 'Kigali'), ('Australia', 'Canberra'), ('Mozambique', 'Maputo'), ('Cabo Verde', 'Praia'), ('Vietnam', 'Hanoi'), ('Iran', 'Tehran'), ('Kosovo', 'Pristina'), ('Jordan', 'Amman'), ('Sao Tome and Principe', 'Sao Tome'), ('Iraq', 'Baghdad'), ('South Korea', 'Seoul'), ('Timor-Leste', 'Dili'), ('Colombia', 'Bogota'), ('Comoros', 'Moroni'), ('Burundi', 'Bujumbura'), ('Syria', 'Damascus'), ('Honduras', 'Tegucigalpa'), ('Uganda', 'Kampala'), ('Thailand', 'Bangkok'), ('Bangladesh', 'Dhaka'), ('Poland', 'Warsaw'), ('Croatia', 'Zagreb'), ('Nigeria', 'Abuja'), ('Vanuatu', 'Port Vila'), ('Philippines', 'Manila'), ('Angola', 'Luanda'), ('Saint Vincent and the Grenadines', 'Kingstown'), ('Germany', 'Berlin'), ('Peru', 'Lima'), ('Russia', 'Moscow'), ('Palestine', 'Jerusalem / Ramallah'), ('Venezuela', 'Caracas'), ('Bahrain', 'Manama'), ('Cyprus', 'Nicosia'), ('Turkey', 'Ankara'), ('Malaysia', 'Kuala Lumpur'), ('Azerbaijan', 'Baku'), ('Saudi Arabia', 'Riyadh'), ('Vatican City (Holy See)', 'Vatican City'), ('Qatar', 'Doha'), ('Uruguay', 'Montevideo'), ('Luxembourg', 'Luxembourg'), ('Liechtenstein', 'Vaduz'), ('Estonia', 'Tallinn'), ('Jamaica', 'Kingston'), ('Guatemala', 'Guatemala City'), ('Saint Kitts and Nevis', 'Basseterre'), ('Central African Republic', 'Bangui'), ('Lesotho', 'Maseru'), ('Singapore', 'Singapore'), ('Kiribati', 'South Tarawa'), ('Antigua and Barbuda', 'Saint Johns'), ('Guyana', 'Georgetown'), ('Monaco', 'Monaco'), ('Andorra', 'Andorra la Vella'), ('Nepal', 'Kathmandu'), ('India', 'New Delhi'), ('Slovenia', 'Ljubljana'), ('Dominican Republic', 'Santo Domingo'), ('Spain', 'Madrid'), ('Lithuania', 'Vilnius'), ('Ireland', 'Dublin'), ('Mongolia', 'Ulaanbaatar'), ('Brunei', 'Bandar Seri Begawan'), ('Kenya', 'Nairobi'), ('Kuwait', 'Kuwait City'), ('Senegal', 'Dakar'), ('Morocco', 'Rabat'), ('South Africa', 'Pretoria'), ('Romania', 'Bucharest'), ('Belize', 'Belmopan'), ('Barbados', 'Bridgetown'), ('Afghanistan', 'Kabul'), ('Maldives', 'Male'), ('United Kingdom', 'London'), ('Moldova', 'Chisinau'), ('Cameroon', 'Yaounde'), ('Bosnia and Herzegovina', 'Sarajevo'), ('Panama', 'Panama City'), ('Ecuador', 'Quito'), ('Montenegro', 'Podgorica'), ('Cambodia', 'Phnom Penh'), ('Greece', 'Athens'), ('Czech Republic', 'Prague'), ('Cuba', 'Havana'), ('Seychelles', 'Victoria'), ('Grenada', 'Saint Georges'), ('Georgia', 'Tbilisi'), ('Italy', 'Rome'), ('Solomon Islands', 'Honiara'), ('United States of America', 'Washington, D.C.'), ('Tunisia', 'Tunis'), ('Republic of the Congo', 'Brazzaville'), ('El Salvador', 'San Salvador'), ('Costa Rica', 'San Jose'), ('Austria', 'Vienna'), ('Chad', "N'Djamena"), ('Paraguay', 'Asuncion'), ('Mauritania', 'Nouakchott'), ('Yemen', 'Sanaa'), ('Papua New Guinea', 'Port Moresby'), ('Netherlands', 'Amsterdam'), ('Indonesia', 'Jakarta'), ('Finland', 'Helsinki'), ('Oman', 'Muscat'), ('Libya', 'Tripoli'), ('Slovakia', 'Bratislava'), ('Uzbekistan', 'Tashkent'), ('Botswana', 'Gaborone'), ('Tonga', 'Nukuʻalofa'), ('Egypt', 'Cairo'), ('Sri Lanka', 'Sri Jayawardenepura Kotte'), ('Namibia', 'Windhoek'), ('Mexico', 'Mexico City'), ('Benin', 'Porto-Novo'), ('Albania', 'Tirana'), ('Swaziland', 'Mbabane'), ('Sierra Leone', 'Freetown'), ('South Sudan', 'Juba'), ('Malta', 'Valletta'), ('Chile', 'Santiago'), ('Portugal', 'Lisbon'), ('Fiji', 'Suva'), ('Bulgaria', 'Sofia'), ('Liberia', 'Monrovia'), ('Haiti', 'Port-au-Prince'), ('Denmark', 'Copenhagen'), ('Argentina', 'Buenos Aires'), ('Armenia', 'Yerevan'), ('Ghana', 'Accra'), ('Guinea-Bissau', 'Bissau'), ('Iceland', 'Reykjavik'), ('Serbia', 'Belgrade'), ('Djibouti', 'Djibouti (city)'), ('Togo', 'Lome'), ('Algeria', 'Algiers'), ('Micronesia', 'Palikir'), ('Sudan', 'Khartoum'), ('Nicaragua', 'Managua'), ('Sweden', 'Stockholm'), ('North Korea', 'Pyongyang'), ('Bhutan', 'Thimphu'), ('Gabon', 'Libreville'), ('Turkmenistan', 'Ashgabat'), ('Democratic Republic of the Congo', 'Kinshasa'), ("Cote d'Ivoire", 'Yamoussoukro'), ('United Arab Emirates', 'Abu Dhabi'), ('Laos', 'Vientiane'), ('Samoa', 'Apia'), ('Belarus', 'Minsk'), ('Belgium', 'Brussels'), ('Marshall Islands', 'Majuro'), ('Niger', 'Niamey'), ('Tuvalu', 'Funafuti'), ('Saint Lucia', 'Castries'), ('Mali', 'Bamako'), ('Canada', 'Ottawa'), ('Switzerland', 'Bern'), ('Somalia', 'Mogadishu'), ('Mauritius', 'Port Louis'), ('Pakistan', 'Islamabad'), ('Taiwan', 'Taipei'), ('Burkina Faso', 'Ouagadougou'), ('Hungary', 'Budapest'), ('Gambia', 'Banjul'), ('Ukraine', 'Kyiv'), ('San Marino', 'San Marino'), ('Trinidad and Tobago', 'Port of Spain'), ('Lebanon', 'Beirut'), ('Latvia', 'Riga'), ('Macedonia', 'Skopje'), ('Tanzania', 'Dodoma')]
